name: Notify Google Chat for Renovate PRs

on:
  pull_request:
    types: [opened]
    branches:
      - feat/n1-prod-payments-k8s
      - feat/prod-main-test
    paths-ignore:
      - '**.md'

jobs:
  notify-google-chat:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'renovate-bot' # Solo para PRs de Renovate
    steps:
      - name: Send Google Chat Notification
        env:
          GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }} # Almacena la URL como secreto
        run: |
          PR_TITLE=$(jq -r .pull_request.title "$GITHUB_EVENT_PATH")
          PR_URL=$(jq -r .pull_request.html_url "$GITHUB_EVENT_PATH")
          PR_AUTHOR=$(jq -r .pull_request.user.login "$GITHUB_EVENT_PATH")
          PR_NUMBER=$(jq -r .pull_request.number "$GITHUB_EVENT_PATH")
          PR_CREATED_AT=$(jq -r .pull_request.created_at "$GITHUB_EVENT_PATH" | awk -F'T' '{print $1}')
          MESSAGE=$(cat <<EOF
          {
            "text": "🔔 *New Renovate PR*\n**Title:** $PR_TITLE\n**URL:** $PR_URL\n**Author:** $PR_AUTHOR\n**Number:** $PR_NUMBER\n**Created:** $PR_CREATED_AT"
          }
          EOF
          )
          curl -X POST -H "Content-Type: application/json" -d "$MESSAGE" "$GOOGLE_CHAT_WEBHOOK_URL"