name: Check and Update Versions with Renovate

on:
  # schedule:
  #   - cron: '*/2 * * * *' # Ejecuta cada 2 minutos (para prueba)
  push:
    branches:
      - feat/prod-payments-k8s
  pull_request:
    branches:
      - feat/prod-payments-k8s
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: feat/prod-payments-k8s
          fetch-depth: 0

      - name: List files in repository
        run: |
          echo "Listing files in the repository:"
          find . -type f

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: "Jocasmen94/k8s-renovate"
          RENOVATE_BASE_BRANCHES: "feat/prod-payments-k8s"
          RENOVATE_BRANCH_PREFIX: "renovate/"
          RENOVATE_PR_CREATION: "immediate"
          RENOVATE_AUTOMERGE: "false"
          RENOVATE_ONBOARDING: "false"
          LOG_LEVEL: "debug"