name: Check and Update Versions with Renovate

on:
  schedule:
    - cron: '*/10 * * * *' # Ejecuta cada 10 minutos
  push:
    branches:
      - prod-payments-k8s
      - feat/prod-payments-k8s
  pull_request:
    branches:
      - prod-payments-k8s
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: prod-payments-k8s
          fetch-depth: 0

      - name: List files in repository
        run: |
          echo "Listing files in the repository:"
          find . -type f

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.4
        env:
          RENOVATE_REPOSITORIES: "Jocasmen94/k8s-renovate" # Especifica el repositorio explícitamente
          RENOVATE_BASE_BRANCHES: "prod-payments-k8s" # Rama base para escaneo
          RENOVATE_TARGET_BRANCH: "feat/prod-payments-k8s" # Rama objetivo para PRs
          RENOVATE_BRANCH_PREFIX: "renovate/"
          RENOVATE_PR_CREATION: "immediate" # Crea PRs inmediatamente
          RENOVATE_AUTOMERGE: false # No automerge para que revises los PRs
          RENOVATE_ONBOARDING: false # Evita el PR de onboarding
          LOG_LEVEL: "debug" # Para depuración
        with:
          configurationFile: renovate.json
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}