name: Check and Update Versions with Renovate

on:
  schedule:
    - cron: '*/20 * * * *' # Ejecuta cada 2 minutos (para prueba)
  push:
    branches:
      - feat/prod-payments-k8s
  pull_request:
    branches:
      - feat/prod-payments-k8s
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Set checkout ref
        id: set_ref
        run: |
          if [[ "${{ github.event_name }}" == "schedule" || "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "pull_request" && "${{ github.ref_name }}" == "feat/prod-payments-k8s" ]]; then
            echo "ref=feat/prod-payments-k8s" >> $GITHUB_OUTPUT
          else
            echo "ref=main" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set_ref.outputs.ref }}
          fetch-depth: 0

      - name: List files in repository
        run: |
          echo "Listing files in the repository:"
          find . -type f

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: "Jocasmen94/k8s-renovate"
          RENOVATE_BASE_BRANCHES: "feat/prod-payments-k8s"
          RENOVATE_BRANCH_PREFIX: "renovate/"
          RENOVATE_PR_CREATION: "immediate"
          RENOVATE_AUTOMERGE: "false"
          RENOVATE_ONBOARDING: "false"
          LOG_LEVEL: "debug"