name: Renovate para prod-main-k8s

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # Cada 10 minutos (opcional)

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout feat/prod-main-k8s
        uses: actions/checkout@v3
        with:
          ref: feat/prod-payments-k8s

      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: renovate.json
