name: Check and Update Versions with Renovate

on:
  schedule:
    - cron: '*/2 * * * *' # Ejecuta cada 2 minutos (para prueba)
  push:
    branches:
      - feat/prod-payments-k8s
      # - main # Eliminado porque no quieres que push en main dispare el workflow
  pull_request:
    branches:
      - feat/prod-payments-k8s
      # - main # Eliminado porque no quieres que PRs a main disparen el workflow
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'schedule' && 'feat/prod-payments-k8s' || github.ref }}
          fetch-depth: 0

      - name: List files in repository
        run: |
          echo "Listing files in the repository:"
          find . -type f

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.4
        env:
          RENOVATE_REPOSITORIES: "Jocasmen94/k8s-renovate"
          RENOVATE_BASE_BRANCHES: "feat/prod-payments-k8s" # Mantenido explícitamente
          RENOVATE_BRANCH_PREFIX: "renovate/"
          RENOVATE_PR_CREATION: "immediate"
          RENOVATE_AUTOMERGE: false
          RENOVATE_ONBOARDING: false
          LOG_LEVEL: "debug"
        with:
          configurationFile: renovate.json # Usará el de main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}