name: Renovate en feat/prod-main-test

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # Ejecutar cada 10 minutos

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
        with:
          ref: feat/prod-main-test

      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
