name: Check and Update Versions with Renovate

on:
  schedule:
    - cron: '*/10 * * * *' # Ejecuta cada 10 minutos
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: prod-payments-k8s # Usa prod-payments-k8s como base
          fetch-depth: 0

      - name: Run Renovate
        uses: renovatebot/github-action@v39.2.4 # Actualizamos a una versión más reciente
        env:
          RENOVATE_BASE_BRANCHES: prod-payments-k8s # Usamos variable de entorno para evitar problemas de sintaxis
          RENOVATE_BRANCH_PREFIX: renovate/ # Prefijo para ramas temporales
          RENOVATE_PR_CREATION: immediate # Crea PRs inmediatamente
          RENOVATE_AUTOMERGE: false # No automerge para que revises los PRs
          RENOVATE_DEFAULT_BRANCH: prod-payments-k8s # Rama por defecto
          RENOVATE_ONBOARDING: false # Evita el PR de onboarding
          LOG_LEVEL: debug # Para depuración
        with:
          configurationFile: renovate.json
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}